version: '3.7'
services:
  mysql:
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'springdb'
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./external/data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    volumes:
      - ./external/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
