spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springdb
    username: 'root'
    password: 'rootpassword'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
#logging:
#  level:
#    root: debug